# Generated by Django 4.2.24 on 2025-09-28 15:59

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("reservation_date", models.DateField()),
                (
                    "reservation_slot",
                    models.SmallIntegerField(
                        choices=[
                            (11, "11:00 AM - 12:00 PM"),
                            (12, "12:00 PM - 1:00 PM"),
                            (13, "1:00 PM - 2:00 PM"),
                            (18, "6:00 PM - 7:00 PM"),
                            (19, "7:00 PM - 8:00 PM"),
                            (20, "8:00 PM - 9:00 PM"),
                            (21, "9:00 PM - 10:00 PM"),
                        ]
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["reservation_date", "reservation_slot"],
                "unique_together": {("reservation_date", "reservation_slot")},
            },
        ),
    ]
